rvm:
  - 1.9.2
notifications:
  recipients:
    - jari.bakken@gmail.com
  irc: "irc.freenode.net#watir"
before_script:
  - support/travis.sh
env:
  - WATIR_WEBDRIVER_BROWSER=firefox ALWAYS_LOCATE=false
  - WATIR_WEBDRIVER_BROWSER=firefox ALWAYS_LOCATE=true
  - WATIR_WEBDRIVER_BROWSER=chrome ALWAYS_LOCATE=false
  - WATIR_WEBDRIVER_BROWSER=chrome ALWAYS_LOCATE=true
