rvm:
  - 1.8.7
  - 1.9.2
  - jruby
  - rbx
notifications:
  recipients:
    - jari.bakken@gmail.com
  irc: "irc.freenode.net#watir"
before_script: 
  - sh -e /etc/init.d/xvfb start
  - git submodule update --init
