rvm:
  - 1.9.2
  - 1.9.3
notifications:
  recipients:
    - jari.bakken@gmail.com
  irc: "irc.freenode.net#watir"
before_script:
  - support/travis.sh
env:
  - WATIR_WEBDRIVER_BROWSER=firefox
  - WATIR_WEBDRIVER_BROWSER=firefox ALWAYS_LOCATE=false
  # - WATIR_WEBDRIVER_BROWSER=firefox NATIVE_EVENTS=true
  - WATIR_WEBDRIVER_BROWSER=chrome
  - WATIR_WEBDRIVER_BROWSER=chrome ALWAYS_LOCATE=false
  # - WATIR_WEBDRIVER_BROWSER=chrome NATIVE_EVENTS=true
