rvm:
  - 1.9.2
notifications:
  recipients:
    - jari.bakken@gmail.com
  irc: "irc.freenode.net#watir"
before_script:
  - sh -e /etc/init.d/xvfb start
  - git submodule update --init
env:
  - WATIR_WEBDRIVER_BROWSER=firefox
